### ISSUE TITLE
Error for complete genomes. 

### ISSUE THREAD

**Issue by OrsonMM** [MatteoPS/EasyPrimer#2]
Dear team EasyPrimer 

I tried to use the program with my data dengue genomes completed. 

But I have a error 

administrador@dengue02:~/programas/EasyPrimer$ python3 EasyPrimer.py -out denv3 -in DENV3_final.fas
Traceback (most recent call last):
  File "EasyPrimer.py", line 449, in <module>
    main()
  File "EasyPrimer.py", line 445, in main
    args.func(args)
  File "EasyPrimer.py", line 407, in run
    primerHRM(out_folder, tmp_folder, inputfile, conslimit, prilen, amplen, prim_thr, amp_thr, n_adj, w_adj, alg, jobname, snp, minpri, maxpri, minamp, maxamp)
  File "EasyPrimer.py", line 150, in primerHRM
    snptab[k][5] = float(snptab[k][0]) / totalleles  # freqA
ZeroDivisionError: float division by zero

Please help !!

**Comment by a-qvecell** [comment]
Hi :) 
Any update on this, EasyPrimer team? I am encounting the same error.
Best regards,

EDIT: 
To anyone getting the same error: 
It is probably caused by your alignment having characters that are not ATGC-. If a position has only non-ATGC--characters, you will have a zerodivision error. 

Amanda
